Support for multiple embedding providers (Huggingface, etc.)
refuel-ai/autolabel pull request #404
Opened 2023-06-27 21:50 UTC by Abhinav-Naikawadi

2023-06-27 22:21 UTC, Abhinav-Naikawadi commented on pyproject.toml
> +    "accelerate == 0.20.3"
This dependency was needed for hugging face pipelines support

2023-06-27 22:21 UTC, Abhinav-Naikawadi commented on pyproject.toml
> +    "ipywidgets == 8.0.6",
This dependency was needed for jupyter notebook support for sentence transformers progress bars

2023-06-27 22:23 UTC, Abhinav-Naikawadi commented on src/autolabel/configs/config.py
> +    def embedding_provider(self) -> str:
We use the LLM provider when an embedding model provider is not specified

2023-06-28 01:04 UTC, nihit commented
Addresses #370

2023-06-28 02:03 UTC, nihit requested changes
@Abhinav-Naikawadi  
1. please add example configs in the PR description here for using HuggingFace and VertexAI embeddings for one of the benchmark tasks.
2. Add tests for verifying the embedding config is correctly used in the few shot initialization class
3. Make relevant changes to config schema for the new embedding key - https://github.com/refuel-ai/autolabel/blob/main/src/autolabel/configs/schema.py

2023-06-28 20:29 UTC, Abhinav-Naikawadi commented
Example config for huggingface embeddings:

{
    "task_name": "BankingComplaintsClassification",
    "task_type": "classification",
    "dataset": {
        "label_column": "label",
        "delimiter": ","
    },
    "model": {
        "provider": "huggingface_pipeline",
        "name": "google/flan-t5-small"
    },
    "embedding": {
        "provider": "huggingface_pipeline",
        "model": "sentence-transformers/all-mpnet-base-v2"
    },
    ...

2023-06-28 20:29 UTC, Abhinav-Naikawadi commented
Example config with google (vertexai) embeddings:
{
    "task_name": "BankingComplaintsClassification",
    "task_type": "classification",
    "dataset": {
        "label_column": "label",
        "delimiter": ","
    },
    "model": {
        "provider": "google",
        "name": "gpt-3.5-turbo"
    },
    "embedding": {
        "provider": "google"
    },
    ...

2023-06-28 22:27 UTC, nihit approved these changes

2023-06-28 22:27 UTC, nihit commented
can merge once tests passing validated

2023-06-28 22:42 UTC, merged